title: 'irfnrdh'
description: "terserah kamu aja deh :v"
baseurl: "/"
url: "https://irfnrdh.github.io"

header_pages:
  - index.md
  - irfnrdh.md
  - about.md
  - contact.md
  - toolkit.md
  - playlist.md

style: dark

footer: 'follow me on <a href="https://twitter.com/irfnrdh">tw</a>, <a href="https://intsgram.com/irfnrdh">ig</a>, <a href="https://www.youtube.com/channel/UCUsEYpI-p0vXLVF2AIEMLIQ?sub_confirmation=1">yt</a>'

# Build settings
markdown: kramdown

remote_theme: ozgrozer/dasper
#b2a3e8/jekyll-theme-console
#piharpi/jekyll-klise
#kronik3r/daktilo
#sharu725/vyaasa




plugins:
  - jekyll-spaceship

