title: 'irfnrdh'
description: "terserah kamu aja deh :v"
baseurl: "/"
url: "https://irfnrdh.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md
  - apps

style: dark

footer: 'ikuti diamnya saya di <a href="https://twitter.com/irfnrdh">tw</a> | <a href="https://intsgram.com/irfnrdh">ig</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
