---
title: irfnrdh
timezone: Europe/London
collections:
  posts:
    title: Daily Notes
    output: true
    description: an abstract journey
  pieces:
    title: Pieces
    output: true
    permalink: pieces
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- garth-jekyll-theme.gemspec
plugins:
- jekyll-paginate
- jekyll-spaceship
paginate: 2
paginate_path: page:num
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
description: terserah kamu aja deh :v
baseurl: "/"
url: https://irfnrdh.github.io
logo: "/assets/logo.svg"
lang: en-GB
remote_theme: daviddarnes/garth
markdown: kramdown
footer: follow me on <a href="https://twitter.com/irfnrdh">tw</a>, <a href="https://intsgram.com/irfnrdh">ig</a>,
  <a href="https://www.youtube.com/channel/UCUsEYpI-p0vXLVF2AIEMLIQ?sub_confirmation=1">yt</a>
header_pages:
- index.md
- irfnrdh.md
- about.md
- contact.md
- toolkit.md
- playlist.md
